apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-microservice-currency-conversion-service-deployment
  labels:
    app: spring-boot-microservice-currency-conversion-service
spec:
  selector:
    matchLabels:
      app: spring-boot-microservice-currency-conversion-service
  template:
    metadata:
      labels:
        app: spring-boot-microservice-currency-conversion-service
    spec:
      containers:
      - name: spring-boot-microservice-currency-conversion-service-container
        image: spring-boot-microservice-currency-conversion-service:1.0-SNAPSHOT
        ports:
        - containerPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-microservice-eureka-naming-server-deployment
  labels:
    app: spring-boot-microservice-eureka-naming-server
spec:
  selector:
    matchLabels:
      app: spring-boot-microservice-eureka-naming-server
  template:
    metadata:
      labels:
        app: spring-boot-microservice-eureka-naming-server
    spec:
      containers:
      - name: spring-boot-microservice-eureka-naming-server-container
        image: spring-boot-microservice-eureka-naming-server:1.0-SNAPSHOT
        ports:
        - containerPort: 8010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-microservice-forex-service-deployment
  labels:
    app: spring-boot-microservice-forex-service
spec:
  selector:
    matchLabels:
      app: spring-boot-microservice-forex-service
  template:
    metadata:
      labels:
        app: spring-boot-microservice-forex-service
    spec:
      containers:
      - name: spring-boot-microservice-forex-service-container
        image: spring-boot-microservice-forex-service:1.0-SNAPSHOT
        ports:
        - containerPort: 8020

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-microservice-currency-conversion-service-service
spec:
  type: NodePort
  selector:
    app: spring-boot-microservice-currency-conversion-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30000

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-microservice-eureka-naming-server-service
spec:
  type: NodePort
  selector:
    app: spring-boot-microservice-eureka-naming-server
  ports:
  - protocol: TCP
    port: 8010
    targetPort: 8010
    nodePort: 30100
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-microservice-forex-service-service
spec:
  type: NodePort
  selector:
    app: spring-boot-microservice-forex-service
  ports:
  - protocol: TCP
    port: 8020
    targetPort: 8020
    nodePort: 30200
